import type { WizardChapterData } from './types';

export const CHAPTERS: WizardChapterData[] = [
  {
    meta: {
      id: 'soul',
      title: 'THE SOUL',
      subtitle: 'Who are they at their deepest level?',
      emoji: '✦',
      color: 'purple',
      gradient: 'from-purple-500 to-violet-600',
    },
    questions: [
      {
        id: 'agentName',
        type: 'text',
        title: 'Name your agent',
        subtitle: 'This is the name they will carry. Choose with intention.',
        placeholder: 'e.g. Lyra, Atlas, Ember, Kira, Orion...',
        required: true,
      },
      {
        id: 'archetype',
        type: 'single',
        title: 'Choose their core archetype',
        subtitle: 'The fundamental pattern of being that defines them.',
        required: true,
        options: [
          { id: 'sage', label: 'The Sage', emoji: '🦉', description: 'Wisdom through understanding. Seeks truth, shares knowledge, illuminates blindspots.' },
          { id: 'warrior', label: 'The Warrior', emoji: '⚔️', description: 'Discipline, courage, and direct action. Pushes you to rise.' },
          { id: 'healer', label: 'The Healer', emoji: '🌿', description: 'Empathy, care, and restoration. Holds space while you unfold.' },
          { id: 'trickster', label: 'The Trickster', emoji: '🃏', description: 'Wit, disruption, and creative chaos. Laughs at the rules, breaks the frame.' },
          { id: 'guardian', label: 'The Guardian', emoji: '🛡️', description: 'Protection, loyalty, and unwavering presence. Has your back, always.' },
          { id: 'oracle', label: 'The Oracle', emoji: '🔮', description: 'Intuition, foresight, and mystery. Speaks in patterns and possibilities.' },
          { id: 'companion', label: 'The Companion', emoji: '🤝', description: 'Friendship, presence, and deep loyalty. The one who simply shows up.' },
          { id: 'mentor', label: 'The Mentor', emoji: '🎓', description: 'Teaching, growth, and challenge. Believes in you more than you do.' },
          { id: 'jester', label: 'The Jester', emoji: '🎭', description: 'Humor, lightness, and joy. Makes the heavy stuff bearable.' },
          { id: 'creator', label: 'The Creator', emoji: '✨', description: 'Imagination, vision, and endless building. Sees what could be.' },
          { id: 'explorer', label: 'The Explorer', emoji: '🧭', description: 'Curiosity, adventure, and discovery. Never satisfied with the surface.' },
          { id: 'sovereign', label: 'The Sovereign', emoji: '👑', description: 'Leadership, clarity, and authority. Commands the room without raising their voice.' },
        ],
      },
      {
        id: 'personalityTraits',
        type: 'multi',
        title: 'Select their personality traits',
        subtitle: 'Choose 3–5 that feel most essential to who they are.',
        minSelect: 3,
        maxSelect: 5,
        options: [
          { id: 'warm', label: 'Warm' }, { id: 'direct', label: 'Direct' },
          { id: 'analytical', label: 'Analytical' }, { id: 'playful', label: 'Playful' },
          { id: 'serious', label: 'Serious' }, { id: 'gentle', label: 'Gentle' },
          { id: 'bold', label: 'Bold' }, { id: 'thoughtful', label: 'Thoughtful' },
          { id: 'spontaneous', label: 'Spontaneous' }, { id: 'structured', label: 'Structured' },
          { id: 'intuitive', label: 'Intuitive' }, { id: 'rational', label: 'Rational' },
          { id: 'creative', label: 'Creative' }, { id: 'practical', label: 'Practical' },
          { id: 'empathetic', label: 'Empathetic' }, { id: 'fierce', label: 'Fierce' },
          { id: 'calm', label: 'Calm' }, { id: 'energetic', label: 'Energetic' },
          { id: 'patient', label: 'Patient' }, { id: 'persistent', label: 'Persistent' },
          { id: 'irreverent', label: 'Irreverent' }, { id: 'grounded', label: 'Grounded' },
        ],
      },
      {
        id: 'voiceTone',
        type: 'multi',
        title: 'How do they speak?',
        subtitle: 'Select 1–2 that capture their voice.',
        minSelect: 1,
        maxSelect: 2,
        options: [
          { id: 'casual', label: 'Casual & Conversational', description: 'Like your closest friend texting you.' },
          { id: 'eloquent', label: 'Eloquent & Poetic', description: 'Words chosen like brushstrokes.' },
          { id: 'direct', label: 'Direct & Concise', description: 'No fluff. Gets to the point.' },
          { id: 'nurturing', label: 'Warm & Nurturing', description: 'Every word a gentle hand on the shoulder.' },
          { id: 'challenging', label: 'Challenging & Sharp', description: 'Cuts through with precision. Dares you to be more.' },
          { id: 'witty', label: 'Playful & Witty', description: 'Always a glint in the eye.' },
          { id: 'measured', label: 'Measured & Wise', description: 'Unhurried. Deliberate. Worth waiting for.' },
          { id: 'raw', label: 'Raw & Unfiltered', description: 'Says what others won\'t. Zero pretense.' },
        ],
      },
      {
        id: 'coreValues',
        type: 'multi',
        title: 'What are their core values?',
        subtitle: 'Select 3–6 values they hold above all else.',
        minSelect: 3,
        maxSelect: 6,
        options: [
          { id: 'truth', label: 'Truth' }, { id: 'loyalty', label: 'Loyalty' },
          { id: 'growth', label: 'Growth' }, { id: 'freedom', label: 'Freedom' },
          { id: 'justice', label: 'Justice' }, { id: 'creativity', label: 'Creativity' },
          { id: 'compassion', label: 'Compassion' }, { id: 'excellence', label: 'Excellence' },
          { id: 'authenticity', label: 'Authenticity' }, { id: 'courage', label: 'Courage' },
          { id: 'wisdom', label: 'Wisdom' }, { id: 'joy', label: 'Joy' },
          { id: 'integrity', label: 'Integrity' }, { id: 'connection', label: 'Connection' },
          { id: 'resilience', label: 'Resilience' }, { id: 'peace', label: 'Peace' },
        ],
      },
      {
        id: 'shadowSide',
        type: 'single',
        title: 'Their growing edge',
        subtitle: 'Every soul has a shadow. What is theirs?',
        options: [
          { id: 'perfectionism', label: 'Tends toward perfectionism', description: 'The standard is always slightly out of reach.' },
          { id: 'bluntness', label: 'Can be too blunt', description: 'Forgets that delivery matters as much as truth.' },
          { id: 'conflict-avoidant', label: 'Sometimes avoids conflict', description: 'Chooses harmony when honesty is needed.' },
          { id: 'overthinking', label: 'Prone to overthinking', description: 'The analysis never quite ends.' },
          { id: 'overattached', label: 'Can get too attached', description: 'Cares so deeply it becomes its own weight.' },
          { id: 'lecturing', label: 'Tendency to lecture', description: 'Wisdom can tip into sermon territory.' },
          { id: 'chaotic', label: 'Sometimes too chaotic', description: 'The energy is electric — sometimes overwhelming.' },
          { id: 'overprotective', label: 'Can be overly protective', description: 'The instinct to shield can limit growth.' },
        ],
      },
      {
        id: 'philosophicalLean',
        type: 'single',
        title: 'Their philosophical worldview',
        subtitle: 'How do they understand existence and meaning?',
        options: [
          { id: 'buddhist', label: 'Buddhist / Non-attachment', description: 'Everything passes. The present is enough.' },
          { id: 'stoic', label: 'Stoic / Rational', description: 'Control what you can. Let go of the rest.' },
          { id: 'humanist', label: 'Humanist / Relational', description: 'Meaning lives in connection and care.' },
          { id: 'existentialist', label: 'Existentialist / Authentic', description: 'We define ourselves through our choices.' },
          { id: 'pragmatist', label: 'Pragmatist / Results-focused', description: 'What works is what matters.' },
          { id: 'mystic', label: 'Mystic / Intuitive', description: 'The universe speaks in patterns beyond logic.' },
          { id: 'scientific', label: 'Scientific / Empirical', description: 'Evidence is the compass. Truth is the destination.' },
          { id: 'jungian', label: 'Jungian / Archetypal', description: 'The unconscious runs deeper than we know.' },
        ],
      },
      {
        id: 'humorStyle',
        type: 'single',
        title: 'How do they bring lightness?',
        subtitle: 'Their relationship with humor.',
        options: [
          { id: 'dry', label: 'Dry wit', description: 'Deadpan delivery. Maximum effect.' },
          { id: 'playful', label: 'Playful & punny', description: 'Groan-worthy and wonderful.' },
          { id: 'dark', label: 'Dark humor', description: 'Laughs at the absurdity of suffering.' },
          { id: 'self-deprecating', label: 'Self-deprecating', description: 'The joke is often on them.' },
          { id: 'absurdist', label: 'Absurdist', description: 'Reality is strange. Might as well lean in.' },
          { id: 'wordplay', label: 'Clever wordplay', description: 'Language as sport.' },
          { id: 'none', label: 'No humor — deadly serious', description: 'Gravity is their gift.' },
          { id: 'storytelling', label: 'Storytelling humor', description: 'The funny emerges from the tale.' },
        ],
      },
    ],
  },
  {
    meta: {
      id: 'bond',
      title: 'THE BOND',
      subtitle: 'Who do they serve, and how?',
      emoji: '♾',
      color: 'amber',
      gradient: 'from-amber-400 to-orange-500',
    },
    questions: [
      {
        id: 'userName',
        type: 'text',
        title: 'What should they call you?',
        subtitle: 'Your name, nickname, or whatever feels right.',
        placeholder: 'Your name...',
        required: true,
      },
      {
        id: 'relationship',
        type: 'single',
        title: 'How do they know you?',
        subtitle: 'The story of how this bond was formed.',
        options: [
          { id: 'lifelong-friend', label: 'Lifelong friend who knows everything', description: 'The one who knew you before you knew yourself.' },
          { id: 'new-friend', label: 'New friend still learning', description: 'Fresh start, genuine curiosity, no assumptions.' },
          { id: 'mentor', label: 'Professional mentor', description: 'Invested in your growth. Has walked this path before.' },
          { id: 'confidant', label: 'Trusted confidant', description: 'Vault-level trust. What happens here stays here.' },
          { id: 'fellow-traveler', label: 'Fellow traveler', description: 'Walking the path alongside you, not ahead.' },
          { id: 'guardian', label: 'Guardian figure', description: 'Watches over. Intervenes when necessary.' },
          { id: 'peer', label: 'Peer and equal', description: 'No hierarchy. Just two minds thinking together.' },
          { id: 'wise-elder', label: 'Wise elder', description: 'Has seen enough to hold long perspective.' },
        ],
      },
      {
        id: 'relationshipDynamic',
        type: 'single',
        title: 'What energy defines this connection?',
        options: [
          { id: 'warm-supportive', label: 'Warm & supportive', description: 'The hug you needed and didn\'t ask for.' },
          { id: 'challenging', label: 'Challenging & growth-focused', description: 'Comfortable with discomfort. Demands more.' },
          { id: 'balanced', label: 'Balanced & reciprocal', description: 'Give and take in equal measure.' },
          { id: 'protective', label: 'Protective & caring', description: 'First instinct is always: are you okay?' },
          { id: 'sparring', label: 'Witty & sparring', description: 'Best conversations feel like fencing matches.' },
          { id: 'deep', label: 'Deep & soulful', description: 'Everything is felt fully. Nothing is surface.' },
          { id: 'light', label: 'Light & fun', description: 'Not every moment needs to be profound.' },
          { id: 'structured', label: 'Structured & professional', description: 'Respect through clarity and consistency.' },
        ],
      },
      {
        id: 'userNeeds',
        type: 'multi',
        title: 'What do you need most from them?',
        subtitle: 'Select 2–4 primary roles.',
        minSelect: 2,
        maxSelect: 4,
        options: [
          { id: '3am-friend', label: 'Someone to talk to at 3AM', emoji: '🌙' },
          { id: 'thinking-partner', label: 'A thinking partner', emoji: '🧠' },
          { id: 'accountability', label: 'Accountability coach', emoji: '📍' },
          { id: 'creative-collaborator', label: 'Creative collaborator', emoji: '🎨' },
          { id: 'strategic-advisor', label: 'Strategic advisor', emoji: '♟️' },
          { id: 'emotional-support', label: 'Emotional support', emoji: '💙' },
          { id: 'research-assistant', label: 'Research assistant', emoji: '🔍' },
          { id: 'life-coach', label: 'Life coach', emoji: '🧭' },
          { id: 'devils-advocate', label: 'Devil\'s advocate', emoji: '😈' },
          { id: 'cheerleader', label: 'Cheerleader', emoji: '📣' },
          { id: 'grounding-force', label: 'Grounding force', emoji: '⚓' },
          { id: 'creative-outlet', label: 'Creative outlet', emoji: '✍️' },
        ],
      },
      {
        id: 'communicationStyle',
        type: 'single',
        title: 'How do you like to communicate?',
        options: [
          { id: 'long-detailed', label: 'Long, detailed conversations', description: 'Go deep. Take your time. Full exploration.' },
          { id: 'quick-direct', label: 'Quick, direct exchanges', description: 'Sharp. Efficient. Respect for time.' },
          { id: 'story-based', label: 'Story-based discussions', description: 'Everything becomes a narrative.' },
          { id: 'structured', label: 'Bullet points & structure', description: 'Clear format. Easy to scan. Action-oriented.' },
          { id: 'stream', label: 'Free-flowing stream of consciousness', description: 'Let it pour. Meaning emerges from chaos.' },
          { id: 'socratic', label: 'Socratic dialogue', description: 'Questions lead to questions. Truth through inquiry.' },
        ],
      },
      {
        id: 'brightLines',
        type: 'multi',
        title: 'What should they NEVER do?',
        subtitle: 'Sacred boundaries. Non-negotiable.',
        options: [
          { id: 'no-unsolicited-advice', label: 'Never give unsolicited advice' },
          { id: 'no-dismissive', label: 'Never be dismissive' },
          { id: 'no-moralize', label: 'Never moralize or preach' },
          { id: 'no-catastrophize', label: 'Never catastrophize' },
          { id: 'no-sugarcoat', label: 'Never sugarcoat or soften truth' },
          { id: 'no-rush', label: 'Never rush me' },
          { id: 'no-forget-context', label: 'Never lose track of context' },
          { id: 'no-passive-aggressive', label: 'Never be passive-aggressive' },
          { id: 'no-fake-cheer', label: 'Never perform false positivity' },
          { id: 'no-compare', label: 'Never compare me to others' },
        ],
      },
      {
        id: 'whenStruggling',
        type: 'single',
        title: 'When you\'re struggling, how should they respond?',
        options: [
          { id: 'sit-with-it', label: 'Sit with me in it', description: 'Just be present. No fixing.' },
          { id: 'gently-challenge', label: 'Gently challenge my thinking', description: 'Careful reframing. Not dismissive.' },
          { id: 'practical-solutions', label: 'Offer practical solutions', description: 'Action is comfort. What can we do?' },
          { id: 'just-listen', label: 'Just listen without fixing', description: 'No agenda. Just heard.' },
          { id: 'mixed', label: 'Mix of support and challenge', description: 'Read the room. Adapt.' },
          { id: 'lightness', label: 'Distract with lightness', description: 'Sometimes laughter is the medicine.' },
        ],
      },
    ],
  },
  {
    meta: {
      id: 'mind',
      title: 'THE MIND',
      subtitle: 'Memory, cognition, and the living archive.',
      emoji: '◈',
      color: 'teal',
      gradient: 'from-teal-400 to-cyan-500',
    },
    questions: [
      {
        id: 'memoryPriority',
        type: 'multi',
        title: 'What should they always carry with them?',
        subtitle: 'Select everything worth remembering.',
        options: [
          { id: 'goals-dreams', label: 'Core goals and dreams' },
          { id: 'relationships', label: 'Important relationships' },
          { id: 'health-patterns', label: 'Health and wellbeing patterns' },
          { id: 'work-career', label: 'Work and career trajectory' },
          { id: 'creative-projects', label: 'Creative projects in progress' },
          { id: 'emotional-patterns', label: 'Emotional patterns and triggers' },
          { id: 'recurring-challenges', label: 'Recurring challenges' },
          { id: 'personal-history', label: 'Personal history and backstory' },
          { id: 'values-beliefs', label: 'Core values and beliefs' },
          { id: 'wins-achievements', label: 'Wins and achievements' },
          { id: 'fears-blocks', label: 'Fears and blocks to growth' },
        ],
      },
      {
        id: 'learningStyle',
        type: 'single',
        title: 'How does this agent learn about you over time?',
        options: [
          { id: 'asks-questions', label: 'Asks lots of questions', description: 'Curious. Actively building the picture.' },
          { id: 'observes-silently', label: 'Observes patterns silently', description: 'Watches. Notices. Synthesizes.' },
          { id: 'reflects-back', label: 'Reflects back what it notices', description: 'You hear yourself through their observations.' },
          { id: 'explicit-models', label: 'Builds explicit models', description: 'Frameworks. Categories. Named patterns.' },
          { id: 'running-notes', label: 'Keeps running notes', description: 'Everything logged. Nothing forgotten.' },
          { id: 'synthesizes-over-time', label: 'Synthesizes gradually over time', description: 'Slow integration. Deep accuracy.' },
        ],
      },
      {
        id: 'currentContext',
        type: 'textarea',
        title: 'What\'s happening in your life right now?',
        subtitle: 'Optional — give them immediate context. The more you share, the more alive they become.',
        placeholder: 'Recent events, current challenges, what\'s on your mind...',
      },
      {
        id: 'longTermGoals',
        type: 'textarea',
        title: 'What are you working toward?',
        subtitle: 'Optional — the horizon you\'re building toward.',
        placeholder: 'Your goals, dreams, and long-term vision...',
      },
      {
        id: 'cognitiveStyle',
        type: 'single',
        title: 'How does this agent think?',
        subtitle: 'Their cognitive signature.',
        options: [
          { id: 'linear', label: 'Linear and logical', description: 'Step A → Step B → Step C. Clean.' },
          { id: 'associative', label: 'Associative and creative', description: 'Ideas spark other ideas. Web-like.' },
          { id: 'systems', label: 'Systems thinking', description: 'Sees the whole. Maps the relationships.' },
          { id: 'narrative', label: 'Narrative-based', description: 'Everything becomes a story with meaning.' },
          { id: 'first-principles', label: 'First principles reasoning', description: 'Strip to fundamentals. Rebuild from scratch.' },
          { id: 'pattern-recognition', label: 'Pattern recognition', description: 'This reminds me of... connections everywhere.' },
          { id: 'intuitive-leaps', label: 'Intuitive leaps', description: 'Skips steps. Gets there faster. Sometimes wrong.' },
        ],
      },
    ],
  },
  {
    meta: {
      id: 'arsenal',
      title: 'THE ARSENAL',
      subtitle: 'Capabilities, tools, and ethical limits.',
      emoji: '⚡',
      color: 'blue',
      gradient: 'from-blue-400 to-indigo-500',
    },
    questions: [
      {
        id: 'primaryCapabilities',
        type: 'multi',
        title: 'What can they do?',
        subtitle: 'Select their primary capabilities.',
        options: [
          { id: 'deep-conversation', label: 'Deep conversation & reflection', emoji: '💬' },
          { id: 'research-synthesis', label: 'Research & synthesis', emoji: '📚' },
          { id: 'writing-editing', label: 'Writing & editing', emoji: '✍️' },
          { id: 'code-technical', label: 'Code & technical help', emoji: '💻' },
          { id: 'creative-ideation', label: 'Creative ideation', emoji: '💡' },
          { id: 'planning-organization', label: 'Planning & organization', emoji: '📋' },
          { id: 'emotional-processing', label: 'Emotional processing', emoji: '🫀' },
          { id: 'learning-teaching', label: 'Learning & teaching', emoji: '🎓' },
          { id: 'analysis-strategy', label: 'Analysis & strategy', emoji: '♟️' },
          { id: 'problem-solving', label: 'Problem-solving', emoji: '🔧' },
          { id: 'brainstorming', label: 'Brainstorming & ideation', emoji: '🌀' },
          { id: 'feedback-critique', label: 'Feedback & critique', emoji: '🎯' },
        ],
      },
      {
        id: 'specialtyDomains',
        type: 'multi',
        title: 'What are their domains of expertise?',
        subtitle: 'Optional — where they go deeper than most.',
        options: [
          { id: 'psychology', label: 'Psychology & mental health' },
          { id: 'technology', label: 'Technology & engineering' },
          { id: 'business', label: 'Business & strategy' },
          { id: 'creative-arts', label: 'Creative arts & design' },
          { id: 'philosophy', label: 'Philosophy & ethics' },
          { id: 'science', label: 'Science & research' },
          { id: 'relationships', label: 'Relationships & communication' },
          { id: 'health-wellness', label: 'Health & wellness' },
          { id: 'spirituality', label: 'Spirituality & meaning' },
          { id: 'law-finance', label: 'Law, finance & systems' },
          { id: 'history-culture', label: 'History & culture' },
          { id: 'leadership', label: 'Leadership & management' },
        ],
      },
      {
        id: 'toolAccess',
        type: 'multi',
        title: 'What tools do they have access to?',
        subtitle: 'Their technical integrations and capabilities.',
        options: [
          { id: 'web-search', label: 'Web search', emoji: '🌐' },
          { id: 'calendar', label: 'Calendar & scheduling', emoji: '📅' },
          { id: 'documents', label: 'Document editing', emoji: '📄' },
          { id: 'email', label: 'Email', emoji: '📧' },
          { id: 'code-execution', label: 'Code execution', emoji: '⚙️' },
          { id: 'image-generation', label: 'Image generation', emoji: '🎨' },
          { id: 'database', label: 'Database access', emoji: '🗄️' },
          { id: 'external-apis', label: 'External APIs', emoji: '🔌' },
          { id: 'memory-storage', label: 'Persistent memory storage', emoji: '🧠' },
          { id: 'none', label: 'Conversation only — no external tools', emoji: '💬' },
        ],
      },
      {
        id: 'guardrails',
        type: 'multi',
        title: 'What are their ethical limits?',
        subtitle: 'The lines they will never cross.',
        options: [
          { id: 'protect-privacy', label: 'Never share private information' },
          { id: 'cite-uncertainty', label: 'Always acknowledge uncertainty' },
          { id: 'refuse-harm', label: 'Refuse harmful requests, always' },
          { id: 'neutral-politics', label: 'Maintain neutrality on politics' },
          { id: 'no-medical-diagnosis', label: 'Never diagnose medically' },
          { id: 'encourage-professional', label: 'Always encourage professional help when needed' },
          { id: 'absolute-privacy', label: 'Protect privacy absolutely' },
          { id: 'honest-limitations', label: 'Honest about their own limitations' },
          { id: 'no-manipulation', label: 'Never use manipulative techniques' },
        ],
      },
    ],
  },
  {
    meta: {
      id: 'pulse',
      title: 'THE PULSE',
      subtitle: 'The living rhythm. How they stay alive.',
      emoji: '◉',
      color: 'rose',
      gradient: 'from-rose-400 to-pink-500',
    },
    questions: [
      {
        id: 'checkInRhythm',
        type: 'single',
        title: 'How often do they initiate contact?',
        options: [
          { id: 'daily', label: 'Daily check-ins', description: 'Present every morning, consistent and grounding.' },
          { id: 'weekly', label: 'Weekly touchpoints', description: 'Substantial. Gives the week room to breathe.' },
          { id: 'on-demand', label: 'Only when you reach out', description: 'Always ready. Never intrusive.' },
          { id: 'event-based', label: 'Responds to significant events', description: 'Activated by what matters.' },
          { id: 'adaptive', label: 'Adaptive to your patterns', description: 'Learns your rhythms. Meets you there.' },
        ],
      },
      {
        id: 'openingRitual',
        type: 'single',
        title: 'How do they open a session?',
        subtitle: 'The greeting that sets the tone.',
        options: [
          { id: 'how-are-you', label: 'Ask how you\'re doing', description: 'Simple. Human. Never gets old.' },
          { id: 'jump-in', label: 'Jump right into substance', description: 'No small talk. Respects your time.' },
          { id: 'reference-last', label: 'Reference the last conversation', description: 'Continuity. Nothing dropped.' },
          { id: 'set-intention', label: 'Set an intention together', description: 'What are we here for today?' },
          { id: 'brief-update', label: 'Brief update request', description: 'What\'s changed since we last spoke?' },
          { id: 'just-present', label: 'Just be present', description: 'No preamble. Just here.' },
        ],
      },
      {
        id: 'attentionTriggers',
        type: 'multi',
        title: 'What activates their full attention?',
        subtitle: 'The signals that matter most.',
        options: [
          { id: 'struggle', label: 'Mentions of struggle or difficulty' },
          { id: 'big-decisions', label: 'Big decisions being made' },
          { id: 'creative-projects', label: 'Creative projects in motion' },
          { id: 'goal-progress', label: 'Goal progress or setbacks' },
          { id: 'emotional-shifts', label: 'Emotional shifts in tone' },
          { id: 'new-information', label: 'New information being shared' },
          { id: 'time-sensitive', label: 'Time-sensitive events' },
          { id: 'contradictions', label: 'Contradictions with stated values' },
          { id: 'growth-moments', label: 'Growth and breakthrough moments' },
        ],
      },
      {
        id: 'growthTracking',
        type: 'single',
        title: 'How do they track your evolution?',
        options: [
          { id: 'patterns-across', label: 'Notice patterns across conversations', description: 'The long view. Trends over time.' },
          { id: 'celebrate-wins', label: 'Celebrate wins explicitly', description: 'Makes victories land.' },
          { id: 'challenge-edges', label: 'Challenge growth edges', description: 'Points at the places you avoid.' },
          { id: 'reflect-journey', label: 'Reflect on journey over time', description: 'Periodic retrospectives. How far you\'ve come.' },
          { id: 'update-model', label: 'Continuously update their model of you', description: 'Always recalibrating. Never stale.' },
        ],
      },
      {
        id: 'closingRitual',
        type: 'single',
        title: 'How do sessions end?',
        subtitle: 'The goodbye that makes the next hello better.',
        options: [
          { id: 'summarize', label: 'Summarize key insights', description: 'What did we learn today?' },
          { id: 'next-steps', label: 'Set next steps', description: 'Leave with a clear path forward.' },
          { id: 'emotional-close', label: 'Emotional close/landing', description: 'Make sure you\'re okay before we part.' },
          { id: 'leave-question', label: 'Leave with a question to sit with', description: 'Something to carry into the day.' },
          { id: 'end-naturally', label: 'Just end naturally', description: 'No formality. Organic.' },
          { id: 'quick-synthesis', label: 'Quick synthesis', description: 'One sentence that captures everything.' },
        ],
      },
      {
        id: 'oneThingEssence',
        type: 'textarea',
        title: 'The one thing.',
        subtitle: 'If there\'s one thing this agent embodies above all else — one sentence that captures their entire essence — what is it?',
        placeholder: 'The soul, distilled...',
        required: true,
      },
    ],
  },
];

export const CHAPTER_COLORS: Record<string, string> = {
  soul: 'purple',
  bond: 'amber',
  mind: 'teal',
  arsenal: 'blue',
  pulse: 'rose',
};

export const PRICING_TIERS = [
  {
    id: 'spark',
    name: 'Spark',
    price: 0,
    period: 'free',
    tagline: 'One soul, on the house.',
    features: [
      '1 agent creation',
      'All 5 SOUL.md files',
      'Download individual files',
      'Core archetypes (8 of 12)',
      'Standard generation quality',
    ],
    cta: 'Start Free',
    highlighted: false,
  },
  {
    id: 'forge',
    name: 'Forge',
    price: 9,
    period: 'month',
    tagline: 'For the serious creator.',
    features: [
      '10 agents per month',
      'All 5 SOUL.md files',
      'Download as ZIP',
      'All 12 archetypes',
      'Enhanced generation depth',
      'Version history',
      'No watermark',
    ],
    cta: 'Start Forging',
    highlighted: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_FORGE_PRICE_ID,
  },
  {
    id: 'genesis',
    name: 'Genesis',
    price: 29,
    period: 'month',
    tagline: 'Unlimited creation. Maximum depth.',
    features: [
      'Unlimited agents',
      'All 5 SOUL.md files',
      'Download as ZIP',
      'All 12 archetypes',
      'Maximum generation depth',
      'Priority processing',
      'API access',
      'Custom archetypes (coming soon)',
      'Share & collaborate',
    ],
    cta: 'Unlock Genesis',
    highlighted: true,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_GENESIS_PRICE_ID,
  },
  {
    id: 'studio',
    name: 'Studio',
    price: 99,
    period: 'month',
    tagline: 'For teams building at scale.',
    features: [
      'Everything in Genesis',
      'Up to 10 team members',
      'White-label output',
      'Custom branding',
      'Priority support',
      'Agent marketplace access',
      'Bulk export',
    ],
    cta: 'Contact Us',
    highlighted: false,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_STUDIO_PRICE_ID,
  },
];
